BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Color" (
	"ID"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"colorBackground"	TEXT [10],
	"colorText"	TEXT [10],
	"colorNav"	TEXT [20],
	"colorFooter"	TEXT [20]
);
CREATE TABLE IF NOT EXISTS "Products" (
	"ID"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"TypeName"	TEXT [50],
	"Price"	INTEGER,
	"Image"	TEXT [100],
	FOREIGN KEY("ID") REFERENCES "Image"("ID-Product") ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "Image" (
	"ID"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"ID-Product"	INTEGER NOT NULL,
	"Image"	TEXT [50]
);
CREATE TABLE IF NOT EXISTS "Admin" (
	"ID"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"UserName"	TEXT [50] NOT NULL UNIQUE,
	"UserPassword"	TEXT [50] NOT NULL
);
CREATE TABLE IF NOT EXISTS "Subscribe" (
	"ID"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"Location"	TEXT [50] NOT NULL,
	"Email"	TEXT [50] NOT NULL UNIQUE
);
COMMIT;
